title: My first jekyll site
email: buhtichka@example.com
description: This is my first ever jekyll site
baseurl: "" 
url: "" 
twitter_username: buhtichkata
github_username:  buhtichka


plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
